apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
      app: redis
  template:
    metadata:
      labels:
        component: redis
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          command: ["redis-server","--requirepass","pass123","--appendonly","yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redisdata
              mountPath: /data
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: redisdata
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    component: redis
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redisdata
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Mi

