apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  type: ClusterIP
  selector:
    component: notifications
    app: myappnotifications
  ports:
    - port: 80
      targetPort: 80
