apiVersion: v1
kind: Service
metadata:
  name: notifications-mysql
  labels:
    app: myappnotificationsdb
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    component: notifications-mysql
    app: myappnotificationsdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-mysql-pv-claim
  labels:
    app: notifications-mysql-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-mysql
  labels:
    app: myappnotificationsdb
spec:
  selector:
    matchLabels:
      component: notifications-mysql
      app: myappnotificationsdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: notifications-mysql
        app: myappnotificationsdb
    spec:
      containers:
        - image: mysql:8
          name: notifications-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: 'notifications'
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: notifications-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: notifications-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: notifications-mysql-pv-claim
